export const CLICK_FOLDER = 'CLICK_FOLDER';
export const GET_TO_PREVIOUS_FOLDER = 'GET_TO_PREVIOUS_FOLDER';
export const GET_TO_NEXT_FOLDER = 'GET_TO_NEXT_FOLDER';
export const SET_STATUS_BACK_BUTTON = 'SET_STATUS_BACK_BUTTON';
export const SET_STATUS_NEXT_BUTTON = 'SET_STATUS_NEXT_BUTTON';
export const OPEN_FORM='OPEN_FORM'
