import * as types from './actionTypes';
import {Item} from 'native-base';

const INITIAL_STATE = {
  builderJson: [
    {
      label: 'User Templets',
      action: 'navigation',
      style: 'usertemplete',
      navigationurl: '/Home/index?id=722abe87-63c4-4748-b77f-0a6a029c3957',
      onclick: '',
      showValidations: false,
      theme: '',
      size: '',
      fieldname: '',
      block: false,
      disableOnInvalid: false,
      mask: false,
      tableView: true,
      alwaysEnabled: false,
      type: 'navigation',
      input: true,
      key: '722abe8763c44748b77f0a6a029c3957',
      childs: [],
    },
    {
      label: 'System Table',
      action: 'navigation',
      style: 'systemtable',
      navigationurl: '/Home/index?id=070ea7e7-6d7b-4b60-a7f6-0c91db07dfb6',
      onclick: '',
      showValidations: false,
      theme: '',
      size: '',
      fieldname: '',
      block: false,
      disableOnInvalid: false,
      mask: false,
      tableView: true,
      alwaysEnabled: false,
      type: 'navigation',
      input: true,
      key: '070ea7e76d7b4b60a7f60c91db07dfb6',
      childs: [
        {
          label: 'UserGroup Table',
          action: 'navigation',
          style: 'usergrouptable',
          navigationurl: '/Home/index?id=7d7dc304-83bc-4e1a-b9d5-1a3e452596d9',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: '7d7dc30483bc4e1ab9d51a3e452596d9',
          childs: [],
        },
        {
          label: 'User Table Design',
          action: 'navigation',
          style: 'usertabledesign',
          navigationurl: '/Home/index?id=4927e97d-bae6-44c5-846e-f46bccd2dd26',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: '4927e97dbae644c5846ef46bccd2dd26',
          childs: [],
        },
      ],
    },
    {
      label: 'User Table',
      action: 'navigation',
      style: 'usertable',
      navigationurl: '/Home/index?id=a9f24f6e-e27d-465e-bda8-170cb07a5372',
      onclick: '',
      showValidations: false,
      theme: '',
      size: '',
      fieldname: '',
      block: false,
      disableOnInvalid: false,
      mask: false,
      tableView: true,
      alwaysEnabled: false,
      type: 'navigation',
      input: true,
      key: 'a9f24f6ee27d465ebda8170cb07a5372',
      childs: [
        {
          label: 'Add Table',
          action: 'navigation',
          style: 'addtable',
          navigationurl: '/Home/index?id=bc808d9d-75be-4702-8c26-ed72c3dae0c8',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: 'bc808d9d75be47028c26ed72c3dae0c8',
          childs: [],
        },
      ],
    },
    {
      label: 'System Templete',
      action: 'navigation',
      style: 'systemtemplete',
      navigationurl: '/Home/index?id=dee822e0-63fa-4c9f-a281-621c2e6fc2a8',
      onclick: '',
      showValidations: false,
      theme: '',
      size: '',
      fieldname: '',
      block: false,
      disableOnInvalid: false,
      mask: false,
      tableView: true,
      alwaysEnabled: false,
      type: 'navigation',
      input: true,
      key: 'dee822e063fa4c9fa281621c2e6fc2a8',
      childs: [
        {
          label: 'Navigation',
          action: 'navigation',
          style: 'navigation',
          navigationurl:
            'HTTP://localhost:33068/Home/index?id=380e62a0-a24e-44a8-9bb8-1fb0a1fa13ec',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: '380e62a0a24e44a89bb81fb0a1fa13ec',
          childs: [],
        },
        {
          type: 'form',
          label: 'Submit',
          id: 'afe9d6a0-cd5a-4ad8-a345-c10df9233d3e',
        },
        {
          label: 'TopMenu Form',
          action: 'navigation',
          style: 'topmenuform',
          navigationurl:
            'HTTP://localhost:33068/Home/index?id=1b3bbe1a-c3ce-40fb-a380-c9fa5ac1bc80',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: '1b3bbe1ac3ce40fba380c9fa5ac1bc80',
          childs: [],
        },
      ],
    },
  ],
  currentDirectory: [
    {
      label: 'User Templets',
      action: 'navigation',
      style: 'usertemplete',
      navigationurl: '/Home/index?id=722abe87-63c4-4748-b77f-0a6a029c3957',
      onclick: '',
      showValidations: false,
      theme: '',
      size: '',
      fieldname: '',
      block: false,
      disableOnInvalid: false,
      mask: false,
      tableView: true,
      alwaysEnabled: false,
      type: 'navigation',
      input: true,
      key: '722abe8763c44748b77f0a6a029c3957',
      childs: [],
    },
    {
      label: 'System Table',
      action: 'navigation',
      style: 'systemtable',
      navigationurl: '/Home/index?id=070ea7e7-6d7b-4b60-a7f6-0c91db07dfb6',
      onclick: '',
      showValidations: false,
      theme: '',
      size: '',
      fieldname: '',
      block: false,
      disableOnInvalid: false,
      mask: false,
      tableView: true,
      alwaysEnabled: false,
      type: 'navigation',
      input: true,
      key: '070ea7e76d7b4b60a7f60c91db07dfb6',
      childs: [
        {
          label: 'UserGroup Table',
          action: 'navigation',
          style: 'usergrouptable',
          navigationurl: '/Home/index?id=7d7dc304-83bc-4e1a-b9d5-1a3e452596d9',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: '7d7dc30483bc4e1ab9d51a3e452596d9',
          childs: [],
        },
        {
          label: 'User Table Design',
          action: 'navigation',
          style: 'usertabledesign',
          navigationurl: '/Home/index?id=4927e97d-bae6-44c5-846e-f46bccd2dd26',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: '4927e97dbae644c5846ef46bccd2dd26',
          childs: [],
        },
      ],
    },
    {
      label: 'User Table',
      action: 'navigation',
      style: 'usertable',
      navigationurl: '/Home/index?id=a9f24f6e-e27d-465e-bda8-170cb07a5372',
      onclick: '',
      showValidations: false,
      theme: '',
      size: '',
      fieldname: '',
      block: false,
      disableOnInvalid: false,
      mask: false,
      tableView: true,
      alwaysEnabled: false,
      type: 'navigation',
      input: true,
      key: 'a9f24f6ee27d465ebda8170cb07a5372',
      childs: [
        {
          label: 'Add Table',
          action: 'navigation',
          style: 'addtable',
          navigationurl: '/Home/index?id=bc808d9d-75be-4702-8c26-ed72c3dae0c8',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: 'bc808d9d75be47028c26ed72c3dae0c8',
          childs: [],
        },
      ],
    },
    {
      label: 'System Templete',
      action: 'navigation',
      style: 'systemtemplete',
      navigationurl: '/Home/index?id=dee822e0-63fa-4c9f-a281-621c2e6fc2a8',
      onclick: '',
      showValidations: false,
      theme: '',
      size: '',
      fieldname: '',
      block: false,
      disableOnInvalid: false,
      mask: false,
      tableView: true,
      alwaysEnabled: false,
      type: 'navigation',
      input: true,
      key: 'dee822e063fa4c9fa281621c2e6fc2a8',
      childs: [
        {
          label: 'Navigation',
          action: 'navigation',
          style: 'navigation',
          navigationurl:
            'HTTP://localhost:33068/Home/index?id=380e62a0-a24e-44a8-9bb8-1fb0a1fa13ec',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: '380e62a0a24e44a89bb81fb0a1fa13ec',
          childs: [],
        },
        {
          type: 'form',
          label: 'Submit',
          id: 'afe9d6a0-cd5a-4ad8-a345-c10df9233d3e',
        },
        {
          label: 'TopMenu Form',
          action: 'navigation',
          style: 'topmenuform',
          navigationurl:
            'HTTP://localhost:33068/Home/index?id=1b3bbe1a-c3ce-40fb-a380-c9fa5ac1bc80',
          onclick: '',
          showValidations: false,
          theme: '',
          size: '',
          fieldname: '',
          block: false,
          disableOnInvalid: false,
          mask: false,
          tableView: true,
          alwaysEnabled: false,
          type: 'navigation',
          input: true,
          key: '1b3bbe1ac3ce40fba380c9fa5ac1bc80',
          childs: [],
        },
      ],
    },
  ],
  statem: 'denrme',
  isNextButtonPassive: true,
  isBackButtonPassive: true,
  backLinks: [],
  nextLinks: [],
};

const folderReducer = (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case types.CLICK_FOLDER:
      return {
        ...state,
        currentDirectory: state.currentDirectory.find(
          x => x['key'] == action.folder.key,
        ).childs,
        isBackButtonPassive: false,
        backLinks: [
          ...state.backLinks,
          {
            key: action.folder.key,
            type: action.folder.type,
            label: action.folder.label,
          },
        ],
        isNextButtonPassive: true,
        nextLinks: [],
      };
    case types.GET_TO_PREVIOUS_FOLDER:
      let lastItem = state.backLinks[state.backLinks.length - 1];
      let isPassive = state.backLinks.length == 1 ? true : false;
      let newCurrentDirectory = state.builderJson;
      state.backLinks.forEach(element => {
        if (element != lastItem) {
          newCurrentDirectory = newCurrentDirectory.filter(
            item => item['key'] == element.key,
          )[0].childs;
        }
      });
      return {
        ...state,
        backLinks: state.backLinks.filter(x => x.key != lastItem.key),
        isBackButtonPassive: isPassive,
        isNextButtonPassive: false,
        currentDirectory: newCurrentDirectory,
        nextLinks: [
          ...state.nextLinks,
          {key: lastItem.key, label: lastItem.label},
        ],
      };
    case types.GET_TO_NEXT_FOLDER: {
      let isNextPassive = state.nextLinks.length == 1 ? true : false;
      let lastItem = state.nextLinks.reverse()[0];
      return {
        ...state,
        nextLinks: state.nextLinks.filter(x => x.key != lastItem.key),
        isBackButtonPassive: false,
        isNextButtonPassive: isNextPassive,
        backLinks: [
          ...state.backLinks,
          {key: lastItem.key, label: lastItem.label},
        ],
        currentDirectory: state.currentDirectory.find(
          x => x['key'] == lastItem.key,
        ).childs,
      };
    }
    case types.SET_STATUS_BACK_BUTTON:
      return state;
    case types.SET_STATUS_NEXT_BUTTON:
      return state;
    default:
      return state;
  }
};

export default folderReducer;
